PROJECT_NAME = KaijuFeeder

# Set platforms to build here, spaced separated. (These are in the separate Makefile.targets)
# They can also be built/cleaned individually: "make gg" and "make gg-clean"
# Possible are: gb gbc pocket megaduck sms gg
#TARGETS=gb pocket megaduck
TARGETS=gb gg

# Builds all targets sequentially
all: $(TARGETS)


# Number of banks (must be a power of 2): A (Automatic), 2, 4, 8, 16, 32...
N_BANKS = A

include $(ZGB_PATH)/src/MakefileCommon